services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Friendsoftypo3\HeadlessMask\:
    resource: '../Classes/*'

  Friendsoftypo3\HeadlessMask\Command\GenerateElementTsCommand:
    tags:
      -
        name: console.command
        command: 'headlessmask:generate'
        description: 'Generate TypoScript of each elements'

